config/routes.rb
GraphStarter::Engine.routes.draw do
  resources :groups

  root 'assets#home'

  get 'categories/:slug(.:format)' => 'categories#show'

  resources :groups do
    member do
      get :users_to_add
    end
  end

  get 'models' => 'models#index', as: :models
  get 'models/:name' => 'models#show', as: :model

  get 'authorizables/user_and_group_search.json' => 'authorizables#user_and_group_search'
  get 'authorizables/:model_slug/:id.:format' => 'authorizables#show'
  put 'authorizables/:model_slug/:id.:format' => 'authorizables#update'

  get ':model_slug' => 'assets#index', as: :assets

  get ':model_slug/new' => 'assets#new', as: :new_asset
  post ':model_slug' => 'assets#create', as: :create_asset

  get ':model_slug/:id(.:format)' => 'assets#show', as: :asset
  get ':model_slug/:id/edit' => 'assets#edit', as: :edit_asset
  put ':model_slug/:id/rate(/:new_rating)' => 'assets#rate', as: :rate_asset
  get ':model_slug/search/:query.json' => 'assets#search', as: :search_assets

  get ':model_slug/:id/destroy' => 'assets#destroy', as: :destroy_asset

  patch ':model_slug/:id' => 'assets#update'
end

app/models/concerns/graph_starter/authorizable.rb
module GraphStarter
  module Authorizable
    extend ActiveSupport::Concern

    included do
      property :private, default: nil
      validates :private, inclusion: {in: [true, false, nil]}

      if GraphStarter.configuration.user_class
        has_many :in, :allowed_users, rel_class: :'GraphStarter::CanAccess', model_class: GraphStarter.configuration.user_class
      end

      has_many :in, :allowed_groups, rel_class: :'GraphStarter::CanAccess', model_class: :'GraphStarter::Group'
    end

    def set_access_levels(model, access_levels)
      records_by_id = model.where(id: access_levels.keys).index_by(&:id)

      model.where_not(id: records_by_id.keys)
        .query_as(:r)
        .match_nodes(this: self)
        .match('r-[rel:CAN_ACCESS]->(this)')
        .delete(:rel).exec

      access_levels.each do |id, level|
        CanAccess.create(from_node: records_by_id[id], to_node: self, level: level)
      end
    end

    module ClassMethods
    end
  end
end

app/models/graph_starter/can_access.rb
module GraphStarter
  class CanAccess
    include Neo4j::ActiveRel

    from_class :any # [:User, :Group] ?
    to_class :any
    type :CAN_ACCESS

    creates_unique

    property :level, default: 'read'
    validates :level, inclusion: {in: %w(read write)}
  end
end

app/models/graph_starter/category.rb
module GraphStarter
  class Category
    include Neo4j::ActiveNode
    self.mapped_label_name = 'Category'

    include Authorizable

    property :name
    property :standardized_name, constraint: :unique

    property :icon_class, type: String

    property :created_at
    property :updated_at

    has_many :in, :assets, origin: :categories

    scope :ordered, -> { order(:name) }

    def self.most_recently_updated
      all.order(:updated_at).last
    end
  end
end

app/models/graph_starter/group.rb
module GraphStarter
  class Group
    include Neo4j::ActiveNode
    self.mapped_label_name = 'Group'

    property :name, type: String

    property :created_at
    property :updated_at

    has_one :in, :parent, model_class: :Group, type: :HAS_SUBGROUP
    has_many :out, :sub_groups, model_class: :Group, type: :HAS_SUBGROUP

    has_many :in, :members, model_class: :User, origin: :groups

    def self.roots
      all(:group).where('NOT(group<-[:HAS_SUBGROUP]-())')
    end

    def self.for_query(query_string)
      query_regex = Regexp.new('.*' + query_string.gsub(/[\s\*]+/, '.*') + '.*', 'i')

      as(:group)
        .where('group.name =~ {query}')
        .params(query: query_regex)
    end

    def addable_users
      User.as(:user)
        .groups(:group, nil, optional: true)
        .where('group.uuid <> ?', id)
        .query.with(:user)
        .proxy_as(User, :user)
    end
  end
end

app/models/graph_starter/image.rb
module GraphStarter
  class Image
    include Neo4j::ActiveNode
    self.mapped_label_name = 'Image'
    include Neo4jrb::Paperclip

    property :title
    property :description
    property :details
    property :original_url
    serialize :details

    has_neo4jrb_attached_file :source
    validates_attachment_content_type :source, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

    def source_url
      default_style = GraphStarter.configuration.default_image_style
      source.present? ? source.url(default_style) : original_url
    end
  end
end

app/models/graph_starter/model.rb
module GraphStarter
  class Model
    include Neo4j::ActiveNode
    self.mapped_label_name = 'Model'

    include Authorizable

    id_property :name

    has_many :out, :properties, origin: :model

    def ruby_model
      name.constantize
    end

    def authorized_properties(user)
      require './lib/query_authorizer'
      query_authorizer = QueryAuthorizer.new(properties(:property))

      query_authorizer.authorized_pluck(:property, user)
    end
  end
end

app/models/graph_starter/property.rb
module GraphStarter
  class Property
    include Neo4j::ActiveNode
    self.mapped_label_name = 'Property'

    include Authorizable

    property :name, index: :exact
    property :ruby_type, index: :exact
    property :created_at
    property :updated_at

    has_one :in, :model, type: :HAS_PROPERTY, model_class: '::GraphStarter::Model'

    def attribute_object
      model.ruby_model.attributes[name]
    end
  end
end

app/controllers/graph_starter/application_controller.rb
module GraphStarter
  class ApplicationController < ::ApplicationController

    before_action :load_session_node

    def load_session_node
      session.delete('this_key_should_never_exist') # Make sure we have a session

      @session_node_thread = Thread.new do
        Session.merge(session_id: session.id).tap do |session_node|
          if current_user && session_node.user.nil?
            session_node.user = current_user
          end

          previous_session_id = session['previous_session_id']
          if previous_session_id && previous_session_id != session.id
            session_node.previous_session = Session.find_by(session_id: previous_session_id)
          end
        end
      end

      session['previous_session_id'] = session.id
    end

    def session_node
      puts 'joining...'
      @session_node_thread.join.value
    end

    protected

    def model_class
      @model_slug = params[:model_slug]
      @model_slug.classify.constantize
    rescue NameError
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/controllers/graph_starter/assets_controller.rb
module GraphStarter
  class AssetsController < ::GraphStarter::ApplicationController
    def home
    end

    def index
      @all_assets = asset_set(:asset, nil)
      @assets = asset_set.to_a
      @title = model_class.name.tableize.humanize

      ids = @assets.map(&:categories).flatten.map(&:id)
      @category_images = Asset.where(id: ids)
                          .query_as(:asset)
                          .match('(asset)-[:HAS_IMAGE]->(image:Image)')
                          .pluck('asset.uuid', :image)

      @category_images = Hash[*@category_images.flatten]
    end

    def search
      assets = asset_set { |scope| scope.for_query(params[:query]) }
      results_data = assets.map do |asset|
        description = model_class.search_properties.map do |property|
          "<b>#{property.to_s.humanize}:</b> #{asset.read_attribute(property)}"
        end.join("<br>")

        {
          title: asset.title,
          url: asset_path(id: asset, model_slug: asset.class.model_slug),
          description: description,
          image: asset.first_image_source_url
        }.reject {|_, v| v.nil? }.tap do |result|
          model_class.search_properties.each do |property|
            result[property] = asset.read_attribute(property)
          end
        end
      end

      # INCLUDE SEARCH QUERY PROPERTIES IN RESULT!!!

      render json: {results: results_data}.to_json
    end

    def show
      @asset = asset
      @title = @asset.title

      if @asset
        # Don't wait
        Thread.new do
          View.record_view(session_node,
                           @asset,
                           browser_string: request.env['HTTP_USER_AGENT'],
                           ip_address: request.remote_ip)
          puts 'ending view thread'
        end
      else
        render file: 'public/404.html', status: :not_found, layout: false
      end
    end

    def edit
      @asset, @access_level = asset_with_access_level
      @title = @asset.title.to_s + ' - Edit'

      render file: 'public/404.html', status: :not_found, layout: false if !@asset
    end

    def update
      @asset = asset
      @asset.update(params[params[:model_slug].singularize])

      if params[:image].present?
        if @asset.class.has_image?
          @asset.image = Image.create(source: params[:image])
        elsif @asset.class.has_images?
          @asset.images << Image.create(source: params[:image])
        end
      end

      redirect_to action: :edit
    end

    def new
      @asset = model_class.new
    end

    def create
      @asset = model_class.create(params[params[:model_slug].singularize])

      if @asset.persisted?
        redirect_to action: :show, id: @asset.id
      else
        flash[:error] = @asset.errors.messages.to_a.map {|pair| pair.join(' ') }.join(' / ')
        redirect_to :back
      end
    end

    def destroy
      asset.destroy

      redirect_to action: :index
    end

    def rate
      if current_user
        rating = asset.rating_for(current_user)
        rating ||= Rating.create(from_node: current_user, to_node: asset)

        new_rating = params[:new_rating].to_i
        new_rating = nil if new_rating.zero?
        rating.update_attribute(:level, new_rating)

        render json: rating
      else
        render json: {}
      end
    end

    def asset_set(var = :asset, limit = 30)
      associations = []
      associations << model_class.image_association
      associations += model_class.category_associations
      associations.compact!

      scope = model_class_scope(var)
      scope = scope.for_category(var, params[:category]) if params[:category].present?
      scope = yield scope if block_given?

      scope = scope.limit(limit)

      scope = apply_associations(scope, var)

      scope
    end

    def asset
      apply_associations(model_class_scope.as(:asset).where('asset.uuid = {id} OR asset.slug = {id}', id: params[:id])).to_a[0].tap do |asset|
        raise ActionController::RoutingError.new('Asset not found') if asset.blank?
      end
    end

    def asset_with_access_level
      scope = model_class_scope.where(uuid: params[:id])
      if defined?(current_user)
        scope.pluck(:asset, :level)
      else
        scope.pluck(:asset, '"read"')
      end.to_a[0]
    end

    def model_class_scope(var = :asset)
      @model_class_scope ||= if defined?(current_user)
        model_class.authorized_for(current_user)
      else
        model_class.all(var)
      end
    end

    def associations
      return @associations if @associations.present?

      @associations = []
      @associations << model_class.image_association
      @associations += model_class.category_associations
      @associations.compact!
      @associations
    end

    def apply_associations(scope, var = :asset)
      if associations.present?
        scope.with_associations(*associations)
      else
        scope
      end
    end
  end
end

app/controllers/graph_starter/authorizables_controller.rb
module GraphStarter
  class AuthorizablesController < ApplicationController
    before_action :require_admin

    before_action :set_object, only: [:show, :update]

    def show
    end

    def update
      @object.update_attribute(:private, params[:private])

      @object.set_access_levels User,
                                access_levels_from_permissions(params[:user_permissions], :user)

      @object.set_access_levels Group,
                                access_levels_from_permissions(params[:group_permissions], :group)

      render :show
    end

    def access_levels_from_permissions(permissions, type)
      (permissions || []).each_with_object({}) do |permission, result|
        result[permission[type][:id]] = permission[:level]
      end
    end

    def user_and_group_search
      @users, @groups = if params[:query].present?

                          [User.for_query(params[:query]), Group.for_query(params[:query])]
                        else
                          [[], []]
                        end
    end

    def change_permissions_modal
      render layout: false
    end

    private

    def set_object
      @object = model_class.find(params[:id])
    end
  end
end

app/controllers/graph_starter/categories_controller.rb
module GraphStarter
  class CategoriesController < ApplicationController
    def show
      @category = category

      render json: @category
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def category
      Asset.find_by(slug: slug)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slug
      params.require(:slug)
    end
  end
end

app/controllers/graph_starter/groups_controller.rb
module GraphStarter
  class GroupsController < ApplicationController
    before_action :require_admin

    before_action :set_group, only: [:show, :edit, :update, :destroy, :users_to_add]

    # GET /groups
    # GET /groups.json
    def index
      @groups = Group.roots
    end

    # GET /groups/1
    # GET /groups/1.json
    def show
    end

    # GET /groups/new
    def new
      @group = Group.new
    end

    # GET /groups/1/edit
    def edit
    end

    # POST /groups
    # POST /groups.json
    def create
      @group = Group.new(group_params)

      respond_to do |format|
        if @group.save
          format.html { redirect_to @group, notice: 'Group was successfully created.' }
          format.json { render :show, status: :created, location: @group }
        else
          format.html { render :new }
          format.json { render json: @group.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /groups/1
    # PATCH/PUT /groups/1.json
    def update
      respond_to do |format|
        if @group.update(group_params)
          format.html { redirect_to @group, notice: 'Group was successfully updated.' }
          format.json { render :show, status: :ok, location: @group }
        else
          format.html { render :edit }
          format.json { render json: @group.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /groups/1
    # DELETE /groups/1.json
    def destroy
      @group.destroy
      respond_to do |format|
        format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def users_to_add
      render json: @group.addable_users
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params[:group][:member_ids].reject!(&:blank?)

      params[:group]
    end
  end
end

app/controllers/graph_starter/models_controller.rb
module GraphStarter
  class ModelsController < ApplicationController
    def index
      @models = Model.all
    end

    def show
      @model = Model.find_by(name: params[:name])
    end
  end
end

app/controllers/graph_starter/properties_controller.rb
module GraphStarter
  class PropertiesController < ApplicationController
    def index
      @properties = Property.all
    end

    def show
      @property = Property.find(params[:id])
    end
  end
end

app/helpers/graph_starter/application_helper.rb
module GraphStarter
  module ApplicationHelper
    def asset_path(asset)
      # graph_starter.asset_path({id: asset.slug, model_slug: asset.class.model_slug}.merge(options))
      # Switched to string for performance
      "/#{asset.class.model_slug}/#{asset.slug}"
    end

    def engine_view(&b)
       yield eval("__FILE__.gsub(Rails.root.to_s, GraphStarter::Engine.root.to_s)",b.binding) 
    end

    def render_body(asset, model_slug)
      views = Dir.glob(Rails.root.join("app/views/#{model_slug}/_body.html.*"))

      partial_path = views.present? ? "#{model_slug}/body" : '/graph_starter/assets/body'

      render partial: partial_path, locals: {asset: asset}
    end

    def present_asset(object)
      yield(AssetPresenter.new(object, self)) if block_given?
    end

    def app_user_is_admin?
      current_user && current_user.respond_to?(:admin?) && current_user.admin?
    end

    def app_user
      defined?(:current_user) ? current_user : nil
    end

    def missing_image_tag
      @missing_image_tag ||= image_tag 'missing.png'
    end

    # I know, right?
    def asset_icon(asset, image = (image_unspecified = true; nil))
      image_url = if !image_unspecified
                    image.source.url if image.present?
                  elsif (asset.class.has_images? || asset.class.has_image?) && asset.first_image_source_url.present?
                    asset.first_image_source_url
                  end

      if image_url
        image_tag image_url, class: 'ui avatar image'
      else
        content_tag :i, '', class: [asset.class.icon_class || 'folder', 'large', 'icon']
      end
    end
  end
end

app/views/graph_starter/assets/_admin_buttons.html.slim
- if asset.persisted?
  .ui.buttons
    a.ui.labeled.icon.button.right.floated data-authorizable="#{asset.to_json}"
      | Permissions

    .or

    a.ui.labeled.icon.button.right.floated href="#{graph_starter.edit_asset_path(id: asset)}"
      i.edit.icon
      | Edit

  .ui.divider

  .ui.buttons
    a.ui.labeled.icon.red.button.right.floated href="#{graph_starter.destroy_asset_path(id: asset)}"
      i.delete.icon
      | Delete

app/views/graph_starter/assets/_associations.html.slim
- as_cards = false if !defined?(as_cards)

- asset.class.authorized_associations.each do |name, association|
  - if association.target_class.ancestors.include?(GraphStarter::Asset)
    - result = asset.send(name)
    - if result.present?
      .item
        .content
          .ui.horizontal.divider = name.to_s.humanize
          .description
            - if as_cards
              .ui.link.cards
                - Array(result).each do |object|
                  = render partial: '/graph_starter/assets/card', locals: {asset: object}
            - else
              .ui.middle.aligned.big.divided.list
                - Array(result).each do |object|
                  .item
                    .content
                      = asset_icon object
                      = link_to object.title, asset_path(object)

app/views/graph_starter/assets/_body.html.slim
- if asset.body.present?
  = asset.body
= render partial: '/graph_starter/assets/images', locals: {asset: asset}

app/views/graph_starter/assets/_card.html.slim
.card
  .content
    - if asset.private?
      .right.floated.meta
        i.hide.large.red.icon
    .header = link_to asset.safe_title, asset_path(asset)
  - if asset.class.has_images? || asset.class.has_image?
    .image
      - if asset.first_image_source_url.present?
        = image_tag asset.first_image_source_url
      - else
        = missing_image_tag
  - categories = Array(asset.categories).sort_by(&:name)
  = render partial: 'graph_starter/assets/extra_card_content', locals: {asset: asset}
  - if categories.present?
    .content
      .ui.relaxed.divided.list
        - categories[0,2].each do |category|
          .item
            = asset_icon(category, (@category_images || {})[category.id])

            .content = link_to category.safe_title, asset_path(category)

        - if categories.size > 2
          .item
            i.ellipsis.horizontal.large.icon
            .content more categories

app/views/graph_starter/assets/_cards.html.slim
- grouped_assets = assets.group_by(&:class)

- grouped_assets.each do |model_class, asset_group|
  - if grouped_assets.size > 1
    h2 = model_class.name.pluralize.humanize

  - properties = model_class.properties

  .ui.link.cards
    = render partial: 'graph_starter/assets/card', collection: asset_group, as: :asset

app/views/graph_starter/assets/_form.html.slim
= form_for @asset, url: url_for(action: action), html: {class: 'ui form', multipart: true} do |f|
  = render partial: 'images', locals: {asset: @asset}

  - if @access_level == 'write'
    .field
      label Add image

      = file_field_tag 'image'

  .field
    label Summary

    = f.text_area :summary

  - @asset.class.authorized_properties_and_levels(current_user).each do |property, level|
    .field
      - editable_properties = GraphStarter.configuration.editable_properties[@asset.class.name.to_sym]
      - can_write = (level == 'write') && !f.nil? && (editable_properties.nil? || editable_properties.map(&:to_s).include?(property.name))

      - if @asset.class.display_property?(property.name) || can_write
        label = property.name.humanize

        = render partial: 'graph_starter/properties/property', locals: {property: property, asset: @asset, form: f, can_write: can_write}

  - @asset.class.authorized_associations.each do |name, association|
    - target_class = association.target_class
    - next if !target_class.ancestors.include?(GraphStarter::Asset)
    javascript:
      var current_#{name} = [];

    .field
      label = name.to_s.humanize

      - field_name = (association.type == :has_many ? "#{name.to_s.singularize}_ids" : "#{name}_id")
      - options = target_class.as(:n).pluck(target_class.name_property, target_class.id_property_name).map {|title, _| [GraphStarter::Asset.sanitize_title(title), _] }.sort_by {|pair| pair.inspect.downcase }

      - html_options = {class: 'ui fluid search dropdown'}
      - html_options[:multiple] = '' if association.type == :has_many
      = f.select field_name, options, {include_blank: 'Please select'}, html_options

  javascript:
    $('.ui.dropdown').dropdown()

  = f.submit action.humanize, class: 'ui button'

app/views/graph_starter/assets/_images.html.slim
- if asset.image_array.present?
  .ui.link.cards
    - asset.image_array.each do |image|
      .card
        .image = image_tag image.source_url, class: 'ui image tiny rounded'
        .content
          .header = image.title if image.title.present?
          - if image.description.present?
            .meta = image.description
        .extra.content
          a.ui.large.green.button href="#{image.source_url}" Full Size

app/views/graph_starter/assets/_property_items.html.slim
.ui.items
  - if asset.class.rated? && defined?(current_user) && current_user
    .item
      .content
        .ui.horizontal.divider Rating
        .description
          .ui.star.rating data-max-rating="5" data-rating="#{asset.rating_level_for(current_user)}"
          coffee:
            $('#right-column .ui.rating').rating
              clearable: true
              onRate: (new_rating) ->
                $.ajax
                  method: 'PUT'
                  url: "/#{model_slug}/#{asset_id}/rate/#{new_rating}"


  - asset.class.authorized_properties(defined?(current_user) && current_user).each do |property|
    - next if !asset.class.display_property?(property.name)
    - next if asset.class.name_property?(property.name) || asset.class.body_property?(property.name)

    - if asset.read_attribute(property.name).present?
      .item
        .content
          .ui.horizontal.divider data-authorizable="#{property.to_json}"
            = property.name.humanize
            - if property.private?
              i.red.hide.icon
          .description
            = render partial: 'graph_starter/properties/property', locals: {property: property, asset: asset, level: 'read', can_write: false}

  - if asset.class.display_property?(:created_at)
    .item
      .content
        .ui.horizontal.divider Created
        .description = asset.created_at

  - if asset.class.display_property?(:updated_at)
    .item
      .content
        .ui.horizontal.divider Last updated
        .description = asset.updated_at

app/views/graph_starter/assets/_search.html.slim
.ui.search
  .ui.icon.input
    input.prompt type="text" placeholder="Search..." style="width: 400px"
    i.search.icon
  .results

app/views/graph_starter/assets/edit.html.slim
= javascript_include_tag 'jquery.datetimepicker', 'data-turbolinks-track' => true
= stylesheet_link_tag    'jquery.datetimepicker', media: 'all', 'data-turbolinks-track' => true


h1 = @asset.name

= render partial: 'form', locals: {action: 'update'}

app/views/graph_starter/assets/home.html.slim
| test

app/views/graph_starter/assets/index.html.slim
- if @assets.present?
  = render partial: 'search'

  javascript:
    $('.ui.search').search({
      onSelect: function (result, response) { window.location.replace(result.url) },
      apiSettings: {url: "/#{@model_slug}/search/{query}.json"}
      })

  .ui.divider

- count = @assets.size
- total_count = @all_assets.count
.stacked.segment Displaying #{[count, total_count].min} of #{number_to_human(total_count)} total

.ui.divider

- if app_user_is_admin?
  a.ui.labeled.icon.button.right.floated href="#{new_asset_path}"
    i.write.icon
    | New


= render partial: 'graph_starter/assets/cards', locals: {assets: @assets}

app/views/graph_starter/assets/new.html.slim
= render partial: 'form', locals: {action: 'create'}

app/views/graph_starter/assets/show.html.slim
javascript:
  var asset_id = '#{@asset.id}';
  var model_slug = '#{@asset.class.model_slug}';

- present_asset(@asset) do |asset_presenter|
  .ui.huge.centered.header
    .content
      = @asset.safe_title


  - left_width, center_width, right_width = asset_presenter.display_column_widths

  .ui.grid
    - if asset_presenter.left_sidebar_exists?
      div class="#{left_width} wide column"
        = render partial: '/graph_starter/assets/dynamic_items', locals: {asset: @asset}

    - if asset_presenter.main_column_exists?
      div class="#{center_width} wide column"
        - if asset_presenter.associations_in_body?
          = render partial: '/graph_starter/assets/associations', locals: {asset: @asset, as_cards: true}
        - else
          = render_body(@asset, @model_slug)

    div class="#{right_width} wide column" id="right-column"
      - if app_user_is_admin?
        = render partial: '/graph_starter/assets/admin_buttons', locals: {asset: @asset}
        = render partial: '/graph_starter/assets/extra_admin_buttons', locals: {asset: @asset}

      = render partial: '/graph_starter/assets/extra_buttons', locals: {asset: @asset}

      - if !asset_presenter.left_sidebar_exists?
        .ui.items
          - if !asset_presenter.associations_in_body?
            = render partial: '/graph_starter/assets/associations', locals: {asset: @asset}
          = render partial: '/graph_starter/assets/recommendations', locals: {asset: @asset}

      = render partial: '/graph_starter/assets/property_items', locals: {asset: @asset}